### ISSUE TITLE
No self link, apply is failing

### ISSUE THREAD

**Issue by jonnymcgow7** [terraform-google-modules/terraform-google-kubernetes-engine#100]
We're following almost exactly the readme spec and terraform plan works fine, but when we run apply we get this error: `* module.gke.google_container_cluster.primary: Resource 'data.google_compute_subnetwork.gke_subnetwork' not found for variable 'data.google_compute_subnetwork.gke_subnetwork.self_link'`

Is this a versioning problem on our end maybe? We've tried going through the other issues and the readme but have struggled to find the source of our problem.  for the provider we have: 
```
provider "google-beta" {
  project     = "project-name"
  region      = "region-name"
}
```

And in main.tf we define the module with that specified provider:
```
module "gke" {
  providers {
    google = "google-beta"
  }
...
```

Any help is much appreciated, thanks.

**Comment by rileykarson** [comment]
Oh! This is an issue present in `2.1.0`. If you restrict your provider to `2.0.0`, or wait for `2.2.0` (hopefully later today / early tomorrow) this will work again.

**Comment by vdt-mik** [comment]
Hi! I have same issue too, but i have the new provider version:
`* provider.google: version = "~> 2.2"
* provider.kubernetes: version = "~> 1.5"
* provider.null: version = "~> 2.1"
* provider.random: version = "~> 2.0"`

**Comment by brendanator** [comment]
I was able to get around this by using the default network for everything. 
```terraform
module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google"
  project_id                 = "${var.project}"
  name                       = "${var.cluster_name}"
  region                     = "${var.region}"
  zones                      = "${var.zones}"
  network                    = "default"
  subnetwork                 = "default"
  ip_range_pods              = "default"
  ip_range_services          = "default"
}
```
I guess this means that I would have to manually create these networks/subnets to use different names?

Either these networks should be automatically generated or the documentation needs updating

**Comment by morgante** [comment]
@rileykarson Can you confirm if this has been fixed in the provider?

**Comment by rileykarson** [comment]
It should have been fixed in `2.2.0`, if you can repro in an isolated config please file an issue.

**Comment by morgante** [comment]
@vdt-mik Any chance you could share your config?

**Comment by aaron-lane** [comment]
@jonnymcgow7 can you please confirm if using version 2.2.0 or greater of the provider fixes this issue?

**Comment by SubhakarKotta** [comment]
> @jonnymcgow7 can you please confirm if using version 2.2.0 or greater of the provider fixes this issue?
I am using the below versions but still facing the same issue.
provider "google" {
  version     = "~> 2.3.0"
  credentials = "${ file(var.credentials) }"
  project     = "${var.project_id}"
  region      = "${var.region}"
}

provider "google-beta" {
  version     = "~> 2.3.0"
  credentials = "${ file(var.credentials) }"
  project     = "${var.project_id}"
  region      = "${var.region}"
}

**Comment by aaron-lane** [comment]
@SubhakarKotta can you please file as issue against https://github.com/terraform-providers/terraform-provider-google?

**Comment by SubhakarKotta** [comment]
> @SubhakarKotta can you please file as issue against https://github.com/terraform-providers/terraform-provider-google?

Issue filed https://github.com/terraform-providers/terraform-provider-google/issues/3746

**Comment by chrislovecnm** [comment]
I am hitting this as well, and I am referencing the networking name in the gke module.

My providers

```terraform
provider "google" {
  version = "2.7.0"
  project = "${var.project_id}"
  region  = "${var.region}"
}

provider "google-beta" {
  version = "2.7.0"
  project = "${var.project_id}"
  region  = "${var.region}"
}
```

snippet from my cluster 

```terraform
module "gke" {

  source = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"
  enable_private_endpoint    = "true"
  enable_private_nodes       = "true"
  // TODO make this configurable
  master_ipv4_cidr_block     = "10.0.0.0/28"

  project_id = "${var.project_id}"
  name       = "${var.cluster_name}"
  region   = "${var.region}"
  zones   = "${var.zones}" // FIXME we may need to convert a list to a string here
  regional   = true
  kubernetes_version    = "1.13.5-gke.10"

  network           = "${module.gke-network.network_name}"
  subnetwork        = "my-subnet" // TODO use a variable??
}
```

**Comment by chrislovecnm** [comment]
I even added 

```terraform
output "name" {
  description = "Cluster name"
  value       = "${module.gke.name}"
  depends_on = [ "${module.gke-network.network_name}" ]
}
```

And that did not help

**Comment by aaron-lane** [comment]
@chrislovecnm could you try using an element of `module.gke-network.subnets_names` for the `subnetwork` argument of `module.gke`?

**Comment by chrislovecnm** [comment]
It is an array, not a singular name, let me workout the syntax 😅

**Comment by aaron-lane** [comment]
`"${element(module.gke-network.subnets_names, 0)}"` should work, assuming the first subnet is the one you want to use.

**Comment by chrislovecnm** [comment]
Wahoo! Yes adding the subnet as a var helped.

**Comment by aaron-lane** [comment]
@chrislovecnm Excellent!
@SubhakarKotta does this solution work for you?

**Comment by SubhakarKotta** [comment]
@aaron-lane  Thanks It worked

**Comment by MichelBoucey** [comment]
Hi Aaron,

Terraform v0.11.14
+ provider.google v2.7.0
+ provider.google-beta v2.7.0
+ provider.kubernetes v1.7.0

I'm stuck on the same error when applying plan.

I tried "${element(module.gke-network.subnets_names, 0)}", but no module by that name.

**Comment by morgante** [comment]
@MichelBoucey How are you creating your network? For that to work, you need `gke-network` module defined in the same Terraform config.

If you can share your Terraform config, we'll be able to help easier.

**Comment by MichelBoucey** [comment]
I knew this module wasn't used so far but it seems the only trick to trigger the discover or creation of  the resource `data.google_compute_subnetwork.gke_subnetwork`...

Well, I'm just following the simple_regional_private example:

provider "google-beta" {
  version = "~> 2.7.0"
  project = "${var.project_id}"
  region  = "${var.region}"
}

data "google_compute_subnetwork" "subnetwork" {
  name    = "${var.subnetwork}"
  project = "${var.project_id}"
  region  = "${var.region}"
}

module "gke" {
  source                  = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"
  project_id              = "${var.project_id}"
  name                    = "${var.project_id}"
  regional                = true
  region                  = "${var.region}"
  network                 = "${var.network}"
  subnetwork              = "${var.subnetwork}"
  ip_range_pods           = "${var.network}-pods"
  ip_range_services       = "${var.network}-services"
  service_account         = "terraform@${var.project_id}.iam.gserviceaccount.com"
  enable_private_endpoint = true
  enable_private_nodes    = true
  master_ipv4_cidr_block  = "172.16.0.0/28"

  master_authorized_networks_config = [{
    cidr_blocks = [{
      cidr_block = "10.0.0.0/28"
      display_name = "VPC"
    }]
  }]
}

data "google_client_config" "default" {}

**Comment by morgante** [comment]
@MichelBoucey What exactly is the error you get? It expects subnetwork name as an input.

**Comment by MichelBoucey** [comment]
I get, exactly as @jonnymcgow7, module.gke.google_container_cluster.primary: Resource 'data.google_compute_subnetwork.gke_subnetwork' not found for variable 'data.google_compute_subnetwork.gke_subnetwork.self_link'

**Comment by morgante** [comment]
@MichelBoucey Where is `var.subnetwork` coming from? Where are you defining your subnet creation?

**Comment by MichelBoucey** [comment]
@morgante I thought it was just a name to provide, not to point at an already created resource , but to create the subnetwork by that name. So, `var.subnetwork` is just a name coming from my terraform.vars.

**Comment by morgante** [comment]
Ah, this module doesn't take care of creating the subnetwork. You need to provide a subnetwork from outside the module, which you can use the [network module](https://github.com/terraform-google-modules/terraform-google-network) to handle.

**Comment by MichelBoucey** [comment]
@morgante Oh thank you very much. It's clearer now. I thought `terraform-google-kubernetes-engine` module was self-suffisant to setup a full `GKE` service as there is for `EKS`. BTW: I'm a great beginner on GCP services...

**Comment by chrislovecnm** [comment]
@morgante we should have an example that builds a network and a cluster as well.  I have some TF that I can contribute, once I get the beta module stuff sorted

**Comment by morgante** [comment]
@chrislovecnm My thoughts exactly. :) I opened #195 to track.

**Comment by DXCanas** [comment]
> ```terraform
>   network                    = "default"
> ```



> I was able to get around this by using the default network for everything.
> 
> ```terraform
> module "gke" {
>   source                     = "terraform-google-modules/kubernetes-engine/google"
>   project_id                 = "${var.project}"
>   name                       = "${var.cluster_name}"
>   region                     = "${var.region}"
>   zones                      = "${var.zones}"
>   network                    = "default"
>   subnetwork                 = "default"
>   ip_range_pods              = "default"
>   ip_range_services          = "default"
> }
> ```
> 
> I guess this means that I would have to manually create these networks/subnets to use different names?
> 
> Either these networks should be automatically generated or the documentation needs updating

I don't really have the need for a shared network, but setting default in this way isn't working for me. _Must_ I create a network despite the fact that the `gcloud` CLI will auto-assign to default?

**Comment by morgante** [comment]
@DXCanas I'm a little unclear on your ask. Most users of this module are using it with a custom network rather than the default VPC network.

If you want to use the default VPC, you should be able to though—you just have to specify it. Is that not working for you?

**Comment by DXCanas** [comment]
@morgante That's exactly right!

I get:
```
Error: Error applying plan:

1 error occurred:
	* module.kubernetes.module.gke.google_container_cluster.primary: 1 error occurred:
	* google_container_cluster.primary: Error waiting for creating GKE cluster: Retry budget exhausted (5 attempts): Secondary range "default" does not exist in network "default", subnetwork "default".
```

With this config:
```
module "gke" {
  source = "terraform-google-modules/kubernetes-engine/google"
  project_id = "kolibri-data-portal"
  name = "kdp-cluster"
  region = "${var.cluster_region}"
  zones = ["${var.cluster_region}-a"]
  network = "default"
  subnetwork = "default"
  ip_range_pods = "default"
  ip_range_services = "default"

  http_load_balancing = true
  horizontal_pod_autoscaling = true
  network_policy = false
}
```

**Comment by morgante** [comment]
Got it, opened #211 to track.
